import random

sexres = ['noo',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          'no',
          'never',
          'No',
          'Please stop',
          'Stop',
          "I'm begging you to stop",
          "Fuck it, sure"]
  
  #0.63% chance of saying yes

aires = ['False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'True',
         'True',
         'True',
         'True',
         'True']

aires2 = ['False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'False',
         'True']

prefixresponse = ["<:eminemwhat:804356532510392340>",
                  "what",
                  "the fuck do you want",
                  "wtf do you want",
                  "maybe try using a command",
                  "shut the fuck up",
                  "try using a command dipshit",
                  "do you not know what a command is?",
                  "dumbass",
                  "retard",
                  "fuck you",
                  "<:imagine:805827665357176843>"]